DROP SCHEMA public CASCADE;
CREATE SCHEMA public;

INSERT INTO "Product" ("name", price, category) VALUES
('Suối nhỏ', 10000, 'BEVERAGE'),
('Suối lớn', 17000, 'BEVERAGE'),
('Revive trắng', 17000, 'BEVERAGE'),
('Revive vàng', 17000, 'BEVERAGE'),
('Nước ngọt', 17000, 'BEVERAGE'),
('Pocari nhỏ', 20000, 'BEVERAGE'),
('Pocari lớn', 30000, 'BEVERAGE'),
('Tăng lực', 20000, 'BEVERAGE'),
('Boost', 20000, 'BEVERAGE'),
('Yessy nha đam', 12000, 'BEVERAGE'),
('Yessy sữa chua', 14000, 'BEVERAGE'),
('Yessy matcha', 14000, 'BEVERAGE'),
('Yessy sữa bắp', 17000, 'BEVERAGE'),
('Thuê vợt', 25000, 'EQUIPMENT'),
('Ống cầu lớn', 300000, 'EQUIPMENT'),
('Cầu', 28000, 'EQUIPMENT'),
('Vớ', 60000, 'EQUIPMENT'),
('Quấn cán', 17000, 'EQUIPMENT');

CREATE TABLE "Court" (
  "courtID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "Booking" (
  "bookingID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "courtID" int,
  "startTime" timestamp,
  "endTime" timestamp,
  "totalHours" decimal(5,2)
);

CREATE TABLE "Payment" (
  "paymentID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "paymentType" varchar,
  "total" decimal(10,2),
  "paymentDate" timestamp,
  "note" varchar
);

CREATE TABLE "PaymentDetail" (
  "paymentDetailID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "paymentID" int,
  "productID" int,
  "bookingID" int,
  "quantity" decimal(10,2),
  "unitPrice" decimal(10,2),
  "subTotal" decimal(10,2)
);

CREATE TABLE "Product" (
  "productID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "price" decimal(10,2),
  "category" varchar
);

CREATE TABLE "TimeSlotPrice" (
  "slotID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "courtID" int,
  "startTime" time,
  "endTime" time,
  "pricePerHour" decimal(10,2),
  "isWeekend" boolean
);

COMMENT ON COLUMN "Court"."name" IS 'Tên sân (Ví dụ: Sân 1, Sân 2, Sân 3)';

COMMENT ON COLUMN "Booking"."courtID" IS 'Khách chơi ở sân nào?';

COMMENT ON COLUMN "Booking"."startTime" IS 'Giờ bắt đầu bấm giờ';

COMMENT ON COLUMN "Booking"."endTime" IS 'Giờ kết thúc';

COMMENT ON COLUMN "Booking"."totalHours" IS 'Tổng số giờ chơi (Ví dụ: 1.5 giờ)';

COMMENT ON COLUMN "Payment"."paymentType" IS 'Ví dụ: Credit Card, PayPal, Cash, Bank Transfer';

COMMENT ON COLUMN "Payment"."total" IS 'Tổng số tiền thanh toán';

COMMENT ON COLUMN "PaymentDetail"."productID" IS 'Có giá trị nếu mua hàng hóa (Nước, Cầu)';

COMMENT ON COLUMN "PaymentDetail"."bookingID" IS 'Có giá trị nếu thanh toán tiền thuê sân';

COMMENT ON COLUMN "PaymentDetail"."quantity" IS 'SỐ LƯỢNG (số chai nước) HOẶC SỐ GIỜ CHƠI (1.5)';

COMMENT ON COLUMN "PaymentDetail"."unitPrice" IS 'Đơn giá lúc thanh toán (Giá 1 chai nước hoặc Giá 1 giờ sân)';

COMMENT ON COLUMN "PaymentDetail"."subTotal" IS 'quantity * unitPrice';

COMMENT ON COLUMN "Product"."name" IS 'Tên sản phẩm';

COMMENT ON COLUMN "Product"."price" IS 'Giá bán hiện tại';

COMMENT ON COLUMN "Product"."category" IS 'Beverage, Equipments, Orthers';

COMMENT ON COLUMN "TimeSlotPrice"."courtID" IS 'Áp dụng cho sân nào? Nếu các sân đồng giá thì có thể bỏ qua cột này';

COMMENT ON COLUMN "TimeSlotPrice"."startTime" IS 'Giờ bắt đầu áp dụng (VD: 17:00:00)';

COMMENT ON COLUMN "TimeSlotPrice"."endTime" IS 'Giờ kết thúc áp dụng (VD: 22:00:00)';

COMMENT ON COLUMN "TimeSlotPrice"."pricePerHour" IS 'Đơn giá của khung giờ này';

COMMENT ON COLUMN "TimeSlotPrice"."isWeekend" IS 'Dành cho trường hợp thứ 7, CN có giá riêng';

ALTER TABLE "Booking" ADD FOREIGN KEY ("courtID") REFERENCES "Court" ("courtID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "PaymentDetail" ADD FOREIGN KEY ("paymentID") REFERENCES "Payment" ("paymentID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "PaymentDetail" ADD FOREIGN KEY ("productID") REFERENCES "Product" ("productID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "PaymentDetail" ADD FOREIGN KEY ("bookingID") REFERENCES "Booking" ("bookingID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "TimeSlotPrice" ADD FOREIGN KEY ("courtID") REFERENCES "Court" ("courtID") DEFERRABLE INITIALLY IMMEDIATE;
